"""empty message

Revision ID: 0585d296e0f6
Revises: 8b272b213e59
Create Date: 2025-12-16 13:19:24.862046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0585d296e0f6'
down_revision = '8b272b213e59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('itemsOwnership', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('itemsOwnership', schema=None) as batch_op:
        batch_op.drop_column('quantity')

    # ### end Alembic commands ###
