"""empty message

Revision ID: 06d79416f88c
Revises: f3c5b8c9da2a
Create Date: 2025-11-25 15:44:25.953648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06d79416f88c'
down_revision = 'f3c5b8c9da2a'
branch_labels = None
depends_on = None


def _column_exists(inspector, table_name: str, column_name: str) -> bool:
    return any(col["name"] == column_name for col in inspector.get_columns(table_name))


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    if 'users' not in inspector.get_table_names():
        return
    with op.batch_alter_table('users', schema=None) as batch_op:
        if not _column_exists(inspector, 'users', 'is_guest'):
            batch_op.add_column(sa.Column('is_guest', sa.Boolean(), nullable=False))
        if _column_exists(inspector, 'users', 'username'):
            batch_op.alter_column('username',
                   existing_type=sa.VARCHAR(length=50),
                   nullable=True)
        if _column_exists(inspector, 'users', 'email'):
            batch_op.alter_column('email',
                   existing_type=sa.VARCHAR(length=120),
                   nullable=True)
        if _column_exists(inspector, 'users', 'password_hash'):
            batch_op.alter_column('password_hash',
                   existing_type=sa.VARCHAR(length=255),
                   nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.drop_column('is_guest')

    # ### end Alembic commands ###
