"""empty message

Revision ID: 500b9b92b724
Revises: c8b34ec0e6c3
Create Date: 2025-12-16 14:27:35.466102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '500b9b92b724'
down_revision = 'c8b34ec0e6c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_quantity', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Item', schema=None) as batch_op:
        batch_op.drop_column('max_quantity')

    # ### end Alembic commands ###
