"""empty message

Revision ID: 79d94f992409
Revises: 9983f7cc1d82
Create Date: 2025-12-01 10:31:38.985601

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '79d94f992409'
down_revision = '9983f7cc1d82'
branch_labels = None
depends_on = None


def upgrade():
    bind = op.get_bind()
    inspector = sa.inspect(bind)

    existing_activity_columns = {col["name"] for col in inspector.get_columns("activity_logs")}
    if "amount" in existing_activity_columns:
        with op.batch_alter_table('activity_logs', schema=None) as batch_op:
            batch_op.drop_column('amount')

    existing_interest_columns = {col["name"] for col in inspector.get_columns("interests")}
    interest_columns_to_drop = [
        'month_progress',
        'monthly_goal',
        'last_suggestions_generated_at',
        'target_unit',
    ]
    if any(col in existing_interest_columns for col in interest_columns_to_drop):
        with op.batch_alter_table('interests', schema=None) as batch_op:
            for column_name in interest_columns_to_drop:
                if column_name in existing_interest_columns:
                    batch_op.drop_column(column_name)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('target_unit', sa.VARCHAR(length=32), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('last_suggestions_generated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('monthly_goal', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('month_progress', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))

    with op.batch_alter_table('activity_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
