"""empty message

Revision ID: 8b272b213e59
Revises: c3dd87197a7c
Create Date: 2025-12-15 17:22:25.249586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b272b213e59'
down_revision = 'c3dd87197a7c'
branch_labels = None
depends_on = None


def _table_exists(inspector, table_name: str) -> bool:
    return table_name in inspector.get_table_names()


def _index_exists(inspector, table_name: str, index_name: str) -> bool:
    return any(index["name"] == index_name for index in inspector.get_indexes(table_name))


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    if not _table_exists(inspector, 'admin_users'):
        op.create_table('admin_users',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('username', sa.String(length=50), nullable=True),
        sa.Column('email', sa.String(length=120), nullable=True),
        sa.Column('password_hash', sa.String(length=255), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('permissions', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('username')
        )
        with op.batch_alter_table('admin_users', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_admin_users_email'), ['email'], unique=True)
        return

    email_index = op.f('ix_admin_users_email')
    if not _index_exists(inspector, 'admin_users', email_index):
        with op.batch_alter_table('admin_users', schema=None) as batch_op:
            batch_op.create_index(email_index, ['email'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admin_users_email'))

    op.drop_table('admin_users')
    # ### end Alembic commands ###
