"""empty message

Revision ID: 9d3fff186e78
Revises: 06d79416f88c
Create Date: 2025-11-26 04:27:24.762810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d3fff186e78'
down_revision = '06d79416f88c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
          batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.text('TRUE')))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
