"""empty message

Revision ID: a679b42fd930
Revises: abcd1234activityname
Create Date: 2025-12-14 16:54:40.317737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a679b42fd930'
down_revision = 'abcd1234activityname'
branch_labels = None
depends_on = None


def _table_exists(inspector, table_name: str) -> bool:
    return table_name in inspector.get_table_names()


def _index_exists(inspector, table_name: str, index_name: str) -> bool:
    return any(index["name"] == index_name for index in inspector.get_indexes(table_name))


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    if not _table_exists(inspector, 'items'):
        op.create_table('items',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('pet_id', sa.Integer(), nullable=False),
        sa.Column('acquired_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('equiped', sa.Boolean(), nullable=False),
        sa.Column('trigger', sa.String(), nullable=True),
        sa.Column('rarity', sa.String(), nullable=True),
        sa.Column('value', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
        with op.batch_alter_table('items', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_items_pet_id'), ['pet_id'], unique=False)
            batch_op.create_index(batch_op.f('ix_items_user_id'), ['user_id'], unique=False)
        return

    pet_index = op.f('ix_items_pet_id')
    user_index = op.f('ix_items_user_id')
    with op.batch_alter_table('items', schema=None) as batch_op:
        if not _index_exists(inspector, 'items', pet_index):
            batch_op.create_index(pet_index, ['pet_id'], unique=False)
        if not _index_exists(inspector, 'items', user_index):
            batch_op.create_index(user_index, ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_items_user_id'))
        batch_op.drop_index(batch_op.f('ix_items_pet_id'))

    op.drop_table('items')
    # ### end Alembic commands ###
