"""empty message

Revision ID: ba68f0ee9a23
Revises: 
Create Date: 2025-11-13 22:49:48.761446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba68f0ee9a23'
down_revision = None
branch_labels = None
depends_on = None


def _table_exists(inspector, table_name: str) -> bool:
    return table_name in inspector.get_table_names()


def _index_exists(inspector, table_name: str, index_name: str) -> bool:
    return any(index["name"] == index_name for index in inspector.get_indexes(table_name))


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)

    users_exists = _table_exists(inspector, 'users')
    users_created = False
    if not users_exists:
        op.create_table('users',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('username', sa.String(length=50), nullable=False),
        sa.Column('email', sa.String(length=120), nullable=False),
        sa.Column('password_hash', sa.String(length=255), nullable=False),
        sa.Column('full_name', sa.String(length=120), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('plan', sa.Enum('FREE', 'FREE_TRIAL', 'PREMIUM', name='plan_type_enum'), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('username')
        )
        with op.batch_alter_table('users', schema=None) as batch_op:
            batch_op.create_index(op.f('ix_users_email'), ['email'], unique=True)
        users_exists = True
        users_created = True

    if users_exists and not users_created:
        user_email_index = op.f('ix_users_email')
        if not _index_exists(inspector, 'users', user_email_index):
            with op.batch_alter_table('users', schema=None) as batch_op:
                batch_op.create_index(user_email_index, ['email'], unique=True)

    if not _table_exists(inspector, 'interests'):
        op.create_table('interests',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=120), nullable=False),
        sa.Column('level', sa.String(length=32), nullable=False),
        sa.Column('goal', sa.String(length=255), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('user_id', 'name', name='uq_user_interest_name')
        )

    if not _table_exists(inspector, 'pets'):
        op.create_table('pets',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('xp', sa.Integer(), nullable=False),
        sa.Column('level', sa.Integer(), nullable=False),
        sa.Column('stage', sa.String(length=50), nullable=False),
        sa.Column('next_evolution_xp', sa.Integer(), nullable=False),
        sa.Column('pet_type', sa.String(length=50), nullable=False),
        sa.Column('current_sprite', sa.String(length=255), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint('xp >= 0', name='ck_pet_xp_non_negative'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('user_id')
        )

    activity_logs_exists = _table_exists(inspector, 'activity_logs')
    activity_logs_created = False
    if not activity_logs_exists:
        op.create_table('activity_logs',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('interest_id', sa.Integer(), nullable=False),
        sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
        sa.Column('xp_earned', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['interest_id'], ['interests.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
        with op.batch_alter_table('activity_logs', schema=None) as batch_op:
            batch_op.create_index(op.f('ix_activity_logs_user_id'), ['user_id'], unique=False)
        activity_logs_exists = True
        activity_logs_created = True

    if activity_logs_exists and not activity_logs_created:
        activity_logs_index = op.f('ix_activity_logs_user_id')
        if not _index_exists(inspector, 'activity_logs', activity_logs_index):
            with op.batch_alter_table('activity_logs', schema=None) as batch_op:
                batch_op.create_index(activity_logs_index, ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_logs_user_id'))

    op.drop_table('activity_logs')
    op.drop_table('pets')
    op.drop_table('interests')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
