"""empty message

Revision ID: c3dd87197a7c
Revises: 5cd8e326a168
Create Date: 2025-12-15 14:40:38.830509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3dd87197a7c'
down_revision = '5cd8e326a168'
branch_labels = None
depends_on = None


asset_type_enum = sa.Enum('PNG', 'RIVE', name='asset_type_enum')


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    asset_type_enum.create(op.get_bind(), checkfirst=True)

    with op.batch_alter_table('Item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('asset_type', asset_type_enum, nullable=False, server_default="PNG"))
        batch_op.add_column(sa.Column('asset_path', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('layer_name', sa.String(), nullable=True))

    with op.batch_alter_table('Item', schema=None) as batch_op:
        batch_op.alter_column('asset_type', server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Item', schema=None) as batch_op:
        batch_op.drop_column('layer_name')
        batch_op.drop_column('asset_path')
        batch_op.drop_column('asset_type')

    asset_type_enum.drop(op.get_bind(), checkfirst=True)

    # ### end Alembic commands ###
