"""empty message

Revision ID: c8b34ec0e6c3
Revises: 0585d296e0f6
Create Date: 2025-12-16 13:55:47.524605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8b34ec0e6c3'
down_revision = '0585d296e0f6'
branch_labels = None
depends_on = None


def _column_exists(inspector, table_name: str, column_name: str) -> bool:
    return any(col["name"] == column_name for col in inspector.get_columns(table_name))


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    if 'Item' not in inspector.get_table_names():
        return
    with op.batch_alter_table('Item', schema=None) as batch_op:
        if not _column_exists(inspector, 'Item', 'description'):
            batch_op.add_column(sa.Column('description', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Item', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
