"""empty message

Revision ID: c8c47ef112c5
Revises: 500b9b92b724
Create Date: 2025-12-16 15:27:28.955696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8c47ef112c5'
down_revision = '500b9b92b724'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('PetStyles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pet_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('hat_id', sa.Integer(), nullable=True),
    sa.Column('sunglasses_id', sa.Integer(), nullable=True),
    sa.Column('color_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['color_id'], ['Item.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['hat_id'], ['Item.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sunglasses_id'], ['Item.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('PetStyles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_PetStyles_pet_id'), ['pet_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('PetStyles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_PetStyles_pet_id'))

    op.drop_table('PetStyles')
    # ### end Alembic commands ###
