"""empty message

Revision ID: e8708d57f4f0
Revises: e7f6c5b4a3d2
Create Date: 2025-12-27 19:22:56.652821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8708d57f4f0'
down_revision = 'e7f6c5b4a3d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.drop_index('ix_goals_completed_at')
        batch_op.drop_index('ix_goals_redeemed_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.create_index('ix_goals_redeemed_at', ['redeemed_at'], unique=False)
        batch_op.create_index('ix_goals_completed_at', ['completed_at'], unique=False)

    # ### end Alembic commands ###
